"""Code generator: a type-checked AST -> portable C11 source.

Design choices:
  * Mort ``int`` maps to ``int64_t``; ``bool`` to C ``bool``.
  * Every user function is emitted as ``mort_<name>`` so a Mort program can
    never collide with a C library symbol.
  * The user's ``main`` becomes ``mort_main`` and a real C ``main`` calls it,
    which sidesteps the int64/int return-type clash.
"""
from . import mort_ast as A

_C_BASE = {
    "i8": "int8_t", "i16": "int16_t", "i32": "int32_t", "i64": "int64_t",
    "u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t", "u64": "uint64_t",
    "bool": "bool", "void": "void",
}


def c_type(t, struct_names=frozenset()):
    """Map a Mort type string to its C spelling.

    '*i32' -> 'int32_t*';  'Point' -> 'struct mort_Point'.
    """
    if t.startswith("*"):
        return c_type(t[1:], struct_names) + "*"
    if t in struct_names:
        return "struct mort_" + t
    return _C_BASE[t]


class CodeGen:
    def __init__(self, program, freestanding=False):
        self.program = program
        self.freestanding = freestanding
        self.struct_names = {s.name for s in program.structs}
        self.lines = []
        self.indent = 0

    def _ct(self, t):
        return c_type(t, self.struct_names)

    def _emit(self, s=""):
        self.lines.append(("    " * self.indent + s) if s else "")

    def generate(self):
        self._emit("// Generated by the Mort compiler -- do not edit by hand.")
        # <stdint.h>/<stdbool.h> are freestanding-safe; <stdio.h> is not.
        if not self.freestanding:
            self._emit("#include <stdio.h>")
        self._emit("#include <stdint.h>")
        self._emit("#include <stdbool.h>")
        self._emit()
        # struct forward declarations (so pointers can cross-reference), then
        # full definitions in declared order.
        if self.program.structs:
            for s in self.program.structs:
                self._emit(f"struct mort_{s.name};")
            self._emit()
            for s in self.program.structs:
                self._gen_struct(s)
                self._emit()
        if not self.freestanding:
            self._emit('static void mort_print(int64_t v) { printf("%lld\\n", (long long)v); }')
            self._emit()
        # prototypes first, so any call order works
        for f in self.program.funcs:
            self._emit(self._signature(f) + ";")
        self._emit()
        for f in self.program.funcs:
            self._gen_fn(f)
            self._emit()
        # Hosted builds get a real C main that calls the user's main; a
        # freestanding object has no entry point (the bootloader supplies one).
        if not self.freestanding:
            self._emit("int main(void) { return (int)mort_main(); }")
        return "\n".join(self.lines) + "\n"

    def _gen_struct(self, s):
        self._emit(f"struct mort_{s.name} {{")
        self.indent += 1
        for fld in s.fields:
            self._emit(f"{self._ct(fld.typ)} f_{fld.name};")
        self.indent -= 1
        self._emit("};")

    def _signature(self, f):
        ret = self._ct(f.ret)
        if f.params:
            params = ", ".join(f"{self._ct(p.typ)} m_{p.name}" for p in f.params)
        else:
            params = "void"
        return f"{ret} mort_{f.name}({params})"

    def _gen_fn(self, f):
        self._emit(self._signature(f) + " {")
        self.indent += 1
        for s in f.body.stmts:
            self._gen_stmt(s)
        self.indent -= 1
        self._emit("}")

    def _gen_stmt(self, s):
        if isinstance(s, A.Let):
            self._emit(f"{self._ct(s.var_type)} m_{s.name} = {self._gen_expr(s.expr)};")
        elif isinstance(s, A.Assign):
            self._emit(f"{self._gen_expr(s.target)} = {self._gen_expr(s.expr)};")
        elif isinstance(s, A.Asm):
            self._emit(f'__asm__ volatile ("{s.text}");')
        elif isinstance(s, A.Return):
            if s.expr is None:
                self._emit("return;")
            else:
                self._emit(f"return {self._gen_expr(s.expr)};")
        elif isinstance(s, A.If):
            self._emit(f"if ({self._gen_expr(s.cond)}) {{")
            self.indent += 1
            for st in s.then.stmts:
                self._gen_stmt(st)
            self.indent -= 1
            if s.els is None:
                self._emit("}")
            else:
                self._emit("} else {")
                self.indent += 1
                if isinstance(s.els, A.If):
                    self._gen_stmt(s.els)
                else:
                    for st in s.els.stmts:
                        self._gen_stmt(st)
                self.indent -= 1
                self._emit("}")
        elif isinstance(s, A.While):
            self._emit(f"while ({self._gen_expr(s.cond)}) {{")
            self.indent += 1
            for st in s.body.stmts:
                self._gen_stmt(st)
            self.indent -= 1
            self._emit("}")
        elif isinstance(s, A.Block):
            self._emit("{")
            self.indent += 1
            for st in s.stmts:
                self._gen_stmt(st)
            self.indent -= 1
            self._emit("}")
        elif isinstance(s, A.ExprStmt):
            self._emit(self._gen_expr(s.expr) + ";")

    def _gen_expr(self, e):
        if isinstance(e, A.IntLit):
            return str(e.value)
        if isinstance(e, A.BoolLit):
            return "true" if e.value else "false"
        if isinstance(e, A.StrLit):
            # a C string literal (static, NUL-terminated) viewed as bytes
            return f'(uint8_t*)"{e.value}"'
        if isinstance(e, A.Var):
            return f"m_{e.name}"
        if isinstance(e, A.Cast):
            return f"(({self._ct(e.target_type)}){self._gen_expr(e.expr)})"
        if isinstance(e, A.StructLit):
            inits = ", ".join(
                f".f_{name} = {self._gen_expr(val)}" for name, val in e.fields)
            return f"(struct mort_{e.name}){{ {inits} }}"
        if isinstance(e, A.FieldAccess):
            return f"({self._gen_expr(e.obj)}).f_{e.field}"
        if isinstance(e, A.Unary):
            return f"({e.op}{self._gen_expr(e.operand)})"
        if isinstance(e, A.Binary):
            return f"({self._gen_expr(e.left)} {e.op} {self._gen_expr(e.right)})"
        if isinstance(e, A.Call):
            args = ", ".join(self._gen_expr(a) for a in e.args)
            name = "mort_print" if e.name == "print" else f"mort_{e.name}"
            return f"{name}({args})"
        raise Exception("unreachable: cannot generate expression")  # pragma: no cover
